### ISSUE TITLE
writing tree don't work

### ISSUE THREAD

**Issue by s-kostyaev** [theodorewiles/org-mind-map#6]
I create simple test org file and try `org-mind-map-write`. I see `unflatten` & `dot` process as emacs children for a long time but nothing happen. Looks like data from emacs doesn't send to unflatten's stdin.

**Comment by the-ted** [comment]
Can you attach your test org file? Also to confirm, you are running M-x org-mind-map-write in the org file buffer? What is the system info?

**Comment by s-kostyaev** [comment]
content of `test.org`:
```
* header
** child1
** child2
*** grand child1
*** grand child2
```
> you are running M-x org-mind-map-write in the org file buffer?

yes

> system info

linux x86_64 gnu emacs 25.2.2

And also my shell is `zsh` but I tried to change it to `bash` and have same issue.

**Comment by Trevoke** [comment]
Have not troubleshooted yet but, on MacOS, can't seem to properly create a PDF file either.

**Comment by Trevoke** [comment]
I tried it manually by doing this:

```
(defun org-mind-map-write-named (name)
  "Create a directed graph output based on the org tree in the current buffer, with name NAME.  To customize, see the org-mind-map group."
  (message (org-mind-map-command name))
  (message (org-mind-map-make-dot (org-mind-map-data)) "%s")
  (if (get-buffer "*org-mind-map-errors*")
      (kill-buffer "*org-mind-map-errors*"))
  (let* ((p (start-process-shell-command "org-mind-map-s" "*org-mind-map-errors*" (org-mind-map-command name))))
    (process-send-string p (org-mind-map-make-dot (org-mind-map-data)))
    (process-send-eof p)
    (set-process-sentinel p 'org-mind-map-update-message)))
```

Then taking the output. In my shell, since I use fish, I did this:

`/usr/local/bin/fish -c "unflatten -l3 | dot -Tpdf -Kdot -o/tmp/foo.org.pdf"`

Then I copied and pasted the make-dotted mind-map data, then I hit `C-d` to send the EOF signal, and it properly generated the file.

So.. I'm not sure what in the code is not replicating that sequence of events, since that's where I figured out what the sequence of events was.

**Comment by jave** [comment]
I also seem to experience this problem.
